### ISSUE TITLE
[Question] ACME certificate resolution

### ISSUE THREAD

**Issue by zaggash** [trajano/trajano-swarm#1]
Nice compose, good find on the daemon, I didn't think about it, just stole it from you :)
On the compose files, I only see network marked as `internal=true`.
How traefik is able to resolv external name withtout binding on the bridge ?

On my setup I have to put at least my Traefik instance on a non `internal` network to get it working and resolv my DNSChallenge with ACME.

Am I missing something on your setup ?

**Comment by trajano** [comment]
It's `ports` that expose it to the world

https://github.com/trajano/trajano-swarm/blob/43baa650eddf963961430a8708c9aeece0cc71c2/edge.yml#L6-L17

I cant' help you much with DNS Challenge because I don't use a DNS provider that supports it.

**Comment by zaggash** [comment]
Yeah probably it not working the same way in regard to the network.
Thanks.
